apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-backend
  namespace: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-backend
  template:
    metadata:
      labels:
        app: cms-backend
    spec:
      containers:
        - name: cms-backend
          image: 154931139523.dkr.ecr.ap-southeast-1.amazonaws.com/cms-backend-tf:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cms-backend-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: cms-backend-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cms-backend-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cms-backend-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cms-backend-secret
                  key: DB_PASSWORD
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cms-backend-secret
                  key: WEATHER_API_KEY
            - name: WEATHER_API_URL
              valueFrom:
                secretKeyRef:
                  name: cms-backend-secret
                  key: WEATHER_API_URL
---
apiVersion: v1
kind: Service
metadata:
  name: cms-backend-service
  namespace: cms
spec:
  selector:
    app: cms-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31780
  type: NodePort
